//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devi
    {
        public int Id_Devis { get; set; }
        public string Nom_Visiteur { get; set; }
        public string Prenom_Visiteur { get; set; }
        public string Email_Visiteur { get; set; }
        public string Tel_Visiteur { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_Article { get; set; }
        public Nullable<int> Qte { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
