//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategorie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubCategorie()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int Id_SubCat { get; set; }
        public string Nom_SubCat { get; set; }
        public string Img_SubCat { get; set; }
        public Nullable<int> Id_Cat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Categorie Categorie { get; set; }
    }
}
